server:
  tcp:
    host: "0.0.0.0"
    port: 9000
    backlog: 3000
  http:
    host: "0.0.0.0"
    port: 8080

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123456"
  database: "dnf_game"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600
  conn_max_idle_time: 600

cache:
  default_expiration: 300
  cleanup_interval: 600

log:
  level: "info"
  is_development: true
